# Generated by Django 5.2.8 on 2026-01-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DimActivite",
            fields=[
                ("id_activite_pk", models.AutoField(primary_key=True, serialize=False)),
                ("activite", models.CharField(max_length=100, unique=True)),
                ("poids_activite", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "db_table": "dim_activite",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimClasse",
            fields=[
                ("id_classe_pk", models.AutoField(primary_key=True, serialize=False)),
                ("classe", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "dim_classe",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimCours",
            fields=[
                ("id_cours_pk", models.AutoField(primary_key=True, serialize=False)),
                ("cours", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "dim_cours",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimCritere",
            fields=[
                ("id_critere_pk", models.AutoField(primary_key=True, serialize=False)),
                ("critere", models.CharField(max_length=100, unique=True)),
                ("poids_critere", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "db_table": "dim_critere",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimEtudiant",
            fields=[
                (
                    "id_etudiant_pk",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("nom_etudiant", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "dim_etudiant",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimFiliere",
            fields=[
                ("id_filiere_pk", models.AutoField(primary_key=True, serialize=False)),
                ("filiere", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "dim_filiere",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimSession",
            fields=[
                ("id_session_pk", models.AutoField(primary_key=True, serialize=False)),
                ("session_label", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "dim_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimTypeSession",
            fields=[
                (
                    "id_typesession_pk",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("type_session", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "dim_typesession",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FaitNotes",
            fields=[
                ("id_fact", models.AutoField(primary_key=True, serialize=False)),
                ("poids_activite", models.DecimalField(decimal_places=2, max_digits=5)),
                ("poids_critere", models.DecimalField(decimal_places=2, max_digits=5)),
                ("note", models.DecimalField(decimal_places=2, max_digits=5)),
                ("note_ponderee", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "db_table": "fact_notes",
                "managed": False,
            },
        ),
    ]
